spring:
  datasource:
    url: jdbc:h2:./dv/demo;AUTO_SERVER=true;
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always

server:
  port: 8889
