spring:
  datasource:
    url: jdbc:h2:./db/demo;AUTO_SERVER=true;
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml
#    init:
#      mode: always

server:
  port: 8889

